### ISSUE TITLE
welcome to js world.

### ISSUE THREAD

**Issue by syyunn** [clovekim/js_basic_study#1]
1. WELCOME! I miss you.

2. Consider using `eslint` with VS Code.
 
3. Differences between `var, let ,const` is important.

4. Asynchronous programming is awesome but extremely difficult to fully understand. I recommend you to read the following link : 
https://www.sohamkamani.com/blog/2016/03/14/wrapping-your-head-around-async-programming/

5. Consider learning `TypeScript` right after finishing your glance over `JS`. Static typing provided by `TS` is my favorite.

5. Please check my {React Native + Typescript} iOS App at the link below (if you have an iPhone) :
https://apple.co/2rD0RP9

**Comment by clovekim** [comment]
Thank you for advice. TS is seems to be useful. And I happen to start
learning react and TS thank you.

2020년 2월 7일 (금) 오전 1:28, Zachary Yoon <notifications@github.com>님이 작성:

**Comment by syyunn** [comment]
With my best regards,
Zachary.

+ps : If your are planning to use React framework, I strongly recommend to use StroryBook UI alongside your project. CDD(Component-driven-dev) combined with TDD(Test-driven-dev) is really important in contemporary front-dev.

+ps2 : and upon the issue of applying coherent style on your web-app, I recommend off-the-shelf-style-bundlers like tachyon. Tachyon is amazingly well equipped to serve as the baseline-style-guideline, so we can implement finest quality of design without any involvement from skilled designers.
